select
    paciente_id,
    nombres,
    apellido_paterno,
    apellido_materno,
    tipo_documento,
    numero_documento,
    (DATE '1970-01-01' + fecha_nacimiento * INTERVAL '1 day')::date as fecha_nacimiento,
    sexo,
    estado_civil,
    grado_instruccion,
    ocupacion,
    celular,
    email,
    direccion,
    (DATE '1970-01-01' + fecha_registro * INTERVAL '1 day')::date as fecha_registro,
    canal_captacion,
    estado_paciente,
    modalidad_preferida,
    sede_id
from {{ source('raw', 'pacientes') }}